import type { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    name: "Cozy Tomato Soup",
    image:
      "https://images.unsplash.com/photo-1629978444632-9f63ba0eff47?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "A warm and comforting classic with basil and a touch of cream.",
    cookTime: "30 min",
    tags: ["Vegetarian", "Gluten Free"],
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "2 cans (28 oz) crushed tomatoes",
      "2 cups vegetable broth",
      "1 tsp sugar",
      "1/2 cup cream (optional)",
      "Salt & pepper, fresh basil",
    ],
    instructions: [
      "Warm olive oil in a pot over medium heat; add onion and cook until soft, 4–5 minutes.",
      "Stir in garlic and cook 30–60 seconds until fragrant.",
      "Add crushed tomatoes, broth, and sugar; bring to a simmer.",
      "Simmer gently 15–20 minutes to meld flavors.",
      "Blend until smooth (immersion blender works great).",
      "Stir in cream if using, season with salt and pepper, and finish with torn basil.",
    ],
  },
  {
    id: 2,
    name: "Crispy Baked Falafel",
    image:
      "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Herby chickpea patties baked to golden perfection.",
    cookTime: "35 min",
    tags: ["Vegan", "Gluten Free"],
    ingredients: [
      "1 can chickpeas, drained",
      "1/2 onion, chopped",
      "2 cloves garlic",
      "1 cup parsley & cilantro",
      "2 tbsp flour (GF if needed)",
      "1 tsp cumin, 1/2 tsp coriander",
      "Salt, pepper, olive oil spray",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C) and line a sheet with parchment; oil lightly.",
      "Pulse chickpeas, onion, garlic, herbs, spices, flour, salt and pepper until a coarse paste forms.",
      "Scoop and form small patties or balls; chill 10 minutes to firm.",
      "Place on sheet, mist with oil, and bake 10–12 minutes; flip.",
      "Bake another 8–10 minutes until deep golden and crisp.",
      "Serve warm with tahini sauce and salad vegetables.",
    ],
  },
  {
    id: 3,
    name: "Pink Berry Smoothie",
    image:
      "https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "A vibrant mix of strawberries, raspberries, and yogurt.",
    cookTime: "5 min",
    tags: ["Vegetarian", "Quick", "Gluten Free"],
    ingredients: [
      "1 cup frozen mixed berries",
      "1 banana",
      "3/4 cup yogurt or alt-milk",
      "1 tsp honey (optional)",
    ],
    instructions: [
      "Add berries, banana, and yogurt (or milk) to a blender.",
      "Blend on high until completely smooth.",
      "Adjust thickness with a splash of milk.",
      "Sweeten with honey if desired and serve immediately.",
    ],
  },
  {
    id: 4,
    name: "Creamy Lemon Pasta",
    image:
      "https://images.unsplash.com/photo-1571777663262-fcc9e6076644?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Bright, creamy pasta with lemon zest and parmesan.",
    cookTime: "20 min",
    tags: ["Vegetarian"],
    ingredients: [
      "8 oz pasta",
      "2 tbsp butter",
      "1/2 cup cream",
      "1 lemon (zest & juice)",
      "1/2 cup grated parmesan",
      "Salt, pepper",
    ],
    instructions: [
      "Cook pasta in salted water until al dente; reserve 1/2 cup cooking water.",
      "Melt butter in a skillet; add cream and lemon zest; warm gently.",
      "Add drained pasta and parmesan; toss to coat.",
      "Loosen with reserved water to a glossy sauce.",
      "Finish with lemon juice, salt and pepper; serve immediately.",
    ],
  },
  {
    id: 5,
    name: "Fudgy Chocolate Brownies",
    image:
      "https://images.unsplash.com/photo-1636743715220-d8f8dd900b87?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Ultra-moist brownies with shiny tops.",
    cookTime: "35 min",
    tags: ["Vegetarian"],
    ingredients: [
      "1/2 cup butter",
      "1 cup sugar",
      "2 eggs",
      "1/3 cup cocoa powder",
      "1/2 cup flour",
      "1 tsp vanilla, pinch salt",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C); line an 8-inch pan.",
      "Melt butter; whisk in sugar, eggs, and vanilla until glossy.",
      "Stir in cocoa, flour, and salt just until combined.",
      "Spread batter in pan and smooth the top.",
      "Bake 20–25 minutes until set at edges but fudgy in center.",
      "Cool completely before slicing.",
    ],
  },
  {
    id: 6,
    name: "Teriyaki Salmon Bowl",
    image:
      "https://plus.unsplash.com/premium_photo-1726768924288-9e39b9aee11e?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Sticky teriyaki salmon over rice with steamed greens.",
    cookTime: "25 min",
    tags: ["Pescetarian", "Gluten Free"],
    ingredients: [
      "2 salmon fillets",
      "1/4 cup tamari (GF soy sauce)",
      "1 tbsp honey",
      "1 tsp grated ginger, 1 clove garlic",
      "Cooked rice, steamed broccoli",
    ],
    instructions: [
      "Whisk tamari, honey, ginger, and garlic in a small pan; simmer to a syrupy glaze.",
      "Pat salmon dry; sear skin-side down in a lightly oiled skillet 3–4 minutes.",
      "Flip and cook 2–3 minutes more to desired doneness.",
      "Brush salmon with glaze and let bubble 30 seconds.",
      "Serve over rice with broccoli; drizzle extra glaze.",
    ],
  },
  {
    id: 7,
    name: "Shrimp & Avocado Salad",
    image:
      "https://plus.unsplash.com/premium_photo-1718821752817-a2611010f8f6?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Citrusy shrimp with creamy avocado and greens.",
    cookTime: "15 min",
    tags: ["Pescetarian", "Gluten Free", "Quick"],
    ingredients: [
      "12 oz cooked shrimp",
      "1 avocado, diced",
      "2 cups mixed greens",
      "1/2 cup cherry tomatoes",
      "Lemon vinaigrette",
    ],
    instructions: [
      "Add greens, tomatoes, shrimp, and avocado to a large bowl.",
      "Drizzle with lemon vinaigrette.",
      "Toss gently to avoid crushing avocado.",
      "Season with salt and pepper and serve.",
    ],
  },
  {
    id: 8,
    name: "Keto Cauliflower Fried Rice",
    image:
      "https://images.unsplash.com/photo-1587995631109-2a8588e991da?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Low-carb fried “rice” with veggies and egg.",
    cookTime: "20 min",
    tags: ["Ketogenic", "Gluten Free", "Quick"],
    ingredients: [
      "1 head cauliflower, riced",
      "2 eggs, beaten",
      "1 cup mixed vegetables",
      "2 tbsp tamari",
      "1 tbsp sesame oil, garlic, scallions",
    ],
    instructions: [
      "Heat sesame oil in a large skillet; sauté garlic 30 seconds.",
      "Add cauliflower rice; cook, stirring, 5–6 minutes.",
      "Push to the side; scramble eggs in the empty space.",
      "Add mixed vegetables and tamari; stir-fry 2–3 minutes.",
      "Finish with scallions and serve hot.",
    ],
  },
  {
    id: 9,
    name: "Zucchini Noodles with Pesto",
    image:
      "https://images.unsplash.com/photo-1645775372267-c0299feab469?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Fresh basil pesto tossed with spiralized zucchini.",
    cookTime: "15 min",
    tags: ["Ketogenic", "Vegetarian", "Gluten Free", "Quick"],
    ingredients: [
      "3 medium zucchini, spiralized",
      "1 cup basil leaves",
      "1/4 cup pine nuts",
      "1/3 cup parmesan",
      "1/3 cup olive oil, garlic, lemon",
    ],
    instructions: [
      "Blend basil, pine nuts, parmesan, olive oil, garlic, and a squeeze of lemon into pesto.",
      "Pat zoodles dry; sauté briefly (1–2 minutes) or leave raw for crunch.",
      "Toss with pesto to coat evenly.",
      "Season to taste and serve immediately.",
    ],
  },
  {
    id: 10,
    name: "Greek Chickpea Salad",
    image:
      "https://images.unsplash.com/photo-1719196339826-c66c13ad5b86?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Crisp cucumbers, tomatoes, olives, and chickpeas.",
    cookTime: "10 min",
    tags: ["Vegan", "Gluten Free", "Quick"],
    ingredients: [
      "1 can chickpeas, rinsed",
      "1 cucumber, diced",
      "1 cup cherry tomatoes",
      "1/4 red onion, sliced",
      "Olives, lemon-oregano dressing",
    ],
    instructions: [
      "Combine chickpeas, cucumber, tomatoes, onion, and olives in a bowl.",
      "Whisk or shake dressing; pour over salad.",
      "Toss gently to coat.",
      "Chill 10 minutes if time allows; serve.",
    ],
  },
  {
    id: 11,
    name: "Veggie Stir-Fry",
    image:
      "https://plus.unsplash.com/premium_photo-1664472637341-3ec829d1f4df?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Colorful veggies in a quick ginger-garlic sauce.",
    cookTime: "15 min",
    tags: ["Vegan", "Quick", "Gluten Free"],
    ingredients: [
      "Broccoli, bell pepper, snap peas, carrots",
      "2 cloves garlic, 1 tsp ginger",
      "2 tbsp tamari, 1 tsp sesame oil",
    ],
    instructions: [
      "Heat oil in a wok and add firm veggies first; stir-fry 2–3 minutes.",
      "Add remaining veggies; cook until crisp-tender.",
      "Stir in garlic and ginger for 30 seconds.",
      "Splash with tamari and sesame oil; toss and serve.",
    ],
  },
  {
    id: 12,
    name: "Overnight Berry Oats",
    image:
      "https://plus.unsplash.com/premium_photo-1689247943271-23a7d5a076c6?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Creamy oats you prep the night before.",
    cookTime: "5 min",
    tags: ["Vegetarian"],
    ingredients: [
      "1/2 cup rolled oats",
      "1/2 cup milk or alt-milk",
      "1/4 cup yogurt",
      "1/2 cup mixed berries",
      "Honey, chia (optional)",
    ],
    instructions: [
      "Add oats, milk, yogurt, and sweetener to a jar; stir well.",
      "Fold in berries and chia if using.",
      "Cover and refrigerate overnight.",
      "Stir and enjoy cold (or warm briefly) the next day.",
    ],
  },
  {
    id: 13,
    name: "Hearty Lentil Soup",
    image:
      "https://plus.unsplash.com/premium_photo-1712678665743-15e3833da37e?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Protein-packed soup with carrots and celery.",
    cookTime: "40 min",
    tags: ["Vegan", "Gluten Free"],
    ingredients: [
      "1 cup dried lentils, rinsed",
      "1 onion, carrot, celery",
      "2 cloves garlic",
      "1 can diced tomatoes",
      "4 cups vegetable broth, bay leaf",
    ],
    instructions: [
      "Sauté onion, carrot, and celery in a pot until softened.",
      "Add garlic; cook 30 seconds.",
      "Stir in lentils, tomatoes, broth, and bay leaf.",
      "Bring to a boil, then simmer 25–30 minutes until lentils are tender.",
      "Season to taste and serve.",
    ],
  },
  {
    id: 14,
    name: "Quinoa Tabbouleh",
    image:
      "https://images.unsplash.com/photo-1647714013867-f62bc1cc2039?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Refreshing parsley-forward salad with lemon.",
    cookTime: "25 min",
    tags: ["Vegan", "Gluten Free"],
    ingredients: [
      "1 cup cooked quinoa (cooled)",
      "1 large bunch parsley, chopped",
      "Mint, tomatoes, cucumber",
      "Lemon juice, olive oil, salt",
    ],
    instructions: [
      "Fluff cooled quinoa into a large bowl.",
      "Add parsley, mint, tomatoes, and cucumber.",
      "Whisk lemon juice with olive oil and salt.",
      "Toss salad with dressing and adjust seasoning.",
      "Chill 10–15 minutes for best flavor.",
    ],
  },
  {
    id: 15,
    name: "Caprese Skewers",
    image:
      "https://plus.unsplash.com/premium_photo-1677619680392-b3573dc64f4d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Cherry tomatoes, mozzarella, and basil on sticks.",
    cookTime: "10 min",
    tags: ["Vegetarian", "Gluten Free", "Quick"],
    ingredients: [
      "Cherry tomatoes",
      "Mini mozzarella balls",
      "Fresh basil leaves",
      "Balsamic glaze, salt",
    ],
    instructions: [
      "Thread tomato, mozzarella, and basil onto small skewers.",
      "Arrange on a platter and sprinkle lightly with salt.",
      "Drizzle with balsamic glaze just before serving.",
    ],
  },
  {
    id: 16,
    name: "Lemon Baked Cod",
    image:
      "https://images.unsplash.com/photo-1649366095449-128ddc5ac76f?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Flaky cod fillets with lemon and herbs.",
    cookTime: "20 min",
    tags: ["Pescetarian", "Gluten Free", "Quick"],
    ingredients: [
      "2 cod fillets",
      "1 lemon (slices & juice)",
      "Olive oil, garlic, parsley",
      "Salt, pepper",
    ],
    instructions: [
      "Preheat oven to 400°F (205°C).",
      "Place cod on a lined sheet; drizzle with oil and lemon juice.",
      "Top with garlic, parsley, and lemon slices; season.",
      "Bake 12–15 minutes until flaky.",
      "Rest 2 minutes and serve.",
    ],
  },
  {
    id: 17,
    name: "Spicy Tuna Lettuce Wraps",
    image:
      "https://images.unsplash.com/photo-1526226462688-cebb826cca38?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Zesty tuna salad tucked in crunchy lettuce.",
    cookTime: "10 min",
    tags: ["Pescetarian", "Ketogenic", "Gluten Free", "Quick"],
    ingredients: [
      "2 cans tuna, drained",
      "2 tbsp mayo or Greek yogurt",
      "Sriracha, lime juice",
      "Butter lettuce leaves",
    ],
    instructions: [
      "Mix tuna with mayo (or yogurt), sriracha, and a squeeze of lime.",
      "Season with salt and pepper to taste.",
      "Spoon into separated lettuce leaves.",
      "Serve immediately while crisp.",
    ],
  },
  {
    id: 18,
    name: "Mushroom Risotto",
    image:
      "https://plus.unsplash.com/premium_photo-1694850980302-f568e6de0f6d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Creamy arborio rice with sautéed mushrooms.",
    cookTime: "35 min",
    tags: ["Vegetarian", "Gluten Free"],
    ingredients: [
      "1 cup arborio rice",
      "8 oz mushrooms, sliced",
      "1/2 onion, chopped",
      "3–4 cups warm vegetable broth",
      "Parmesan, butter",
    ],
    instructions: [
      "Sauté mushrooms in a little butter until browned; remove and set aside.",
      "Cook onion in the same pan until translucent; stir in rice 1–2 minutes.",
      "Add warm broth a ladle at a time, stirring until absorbed before adding more.",
      "Continue 16–18 minutes until rice is creamy and just tender.",
      "Fold in mushrooms, parmesan, and a knob of butter; season and rest 1 minute.",
      "Serve immediately while glossy.",
    ],
  },
  {
    id: 19,
    name: "Shakshuka",
    image:
      "https://images.unsplash.com/photo-1682622110419-b671026a4536?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Eggs poached in spiced tomato-pepper sauce.",
    cookTime: "30 min",
    tags: ["Vegetarian", "Gluten Free"],
    ingredients: [
      "1 onion, 1 bell pepper",
      "2 cloves garlic",
      "1 can crushed tomatoes",
      "1 tsp paprika, 1/2 tsp cumin",
      "4–6 eggs",
    ],
    instructions: [
      "Sauté onion and bell pepper in oil until soft.",
      "Add garlic and spices; cook 30 seconds.",
      "Pour in crushed tomatoes; simmer 8–10 minutes to thicken.",
      "Make small wells; crack in eggs.",
      "Cover and cook until whites set and yolks are still soft.",
      "Garnish with herbs and serve with bread.",
    ],
  },
  {
    id: 20,
    name: "Peanut Noodle Salad",
    image:
      "https://images.unsplash.com/photo-1648421778395-82d9881acf72?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Sesame-peanut dressed noodles with crunchy veg.",
    cookTime: "20 min",
    tags: ["Vegetarian"],
    ingredients: [
      "8 oz noodles",
      "1/3 cup peanut butter",
      "2 tbsp soy/tamari, 1 tbsp rice vinegar",
      "1 tsp sesame oil, lime, chili",
      "Carrot, cucumber, scallions",
    ],
    instructions: [
      "Cook noodles according to package; rinse cool and drain well.",
      "Whisk peanut butter with soy/tamari, vinegar, sesame oil, lime, and chili.",
      "Toss noodles with dressing until coated.",
      "Fold in sliced veggies and scallions.",
      "Adjust seasoning and serve chilled or room temp.",
    ],
  },
];
